version: 2.0.{build}

branches:
  only:
    - master

skip_commits:
  files:
    - "*.yml"
    - "*.rst"
    - "LICENSE"
    - "README.MD"
    
install:
  - set QTDIR=C:\Qt\5.12.1\mingw73_64
  - set MINGW64DIR=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\5.12.1\Tools\mingw730_64\bin;%MINGW64DIR%\bin;
build_script:
  - cmd: cd srun-3k-ui"
  - qmake srun-3k-ui.pro
  - mingw32-make
after_build:
  - windeployqt release/SRUN3K.exe
  - rm !(release/SRUN3K.exe|release/platforms|release/libcrypto-1_1-x64.dll|release/libgcc_s_seh-1.dll|release/libssl-1_1-x64.dll|release/libstdc++-6.dll|release/libwinpthread-1.dll|release/Qt5Core.dll|release/Qt5Gui.dll|release/Qt5Widgets.dll) 
  - ls -al release/*
  - cmd: cp ../LICENSE release/LICENSE.txt"
  - cmd: cp ../README.MD release/README.MD"
  - cmd: cp ./server.json release/server.json"
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: release/*
  - path: release
    type: zip
    
notifications:
  - provider: Email
    to:
      - chn-student@Outlook.com
    on_build_status_changed: true