version: 2.0.{build}

branches:
  only:
    - master
    - dev

skip_commits:
  files:
    - "*.yml"
    - "*.rst"
    - "LICENSE"
    - "README.MD"
    
install:
  - set QTDIR=C:\Qt\5.12.1\mingw73_64
  - set MINGW64DIR=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\5.12.1\Tools\mingw730_64\bin;%MINGW64DIR%\bin;
build_script:
  - cmd: cd srun-3k-ui
  - qmake srun-3k-ui.pro
  - mingw32-make
after_build:
  - windeployqt.exe --release --no-translations --no-angle --no-opengl-sw --no-svg --no-webkit2 release/SRUN3K.exe
  - rm -rf release/styles
  - rm -rf release/imageformats
  - cmd: cp ../LICENSE release/LICENSE
  - cmd: cp ../README.MD release/README.MD
  - cmd: cp ./server.json release/server.json
  - rm -rf release/*.o
  - rm -rf release/*.cpp
  # Start packing
  - echo %appveyor_build_version%
  - cd release
  - 7z a (AutoCIBuild)LastRelease.%appveyor_build_version%.7z -mx9 * -r
  - 7z a (AutoCIBuild)MainProgramUpdateSingel.%appveyor_build_version%.7z -mx9 SRUN3K.exe
  
test: off  

artifacts:
  - path: .\release\(AutoCIBuild)LastRelease.%appveyor_build_version%.7z
  - path: .\release\(AutoCIBuild)MainProgramUpdateSingel.%appveyor_build_version%.7z
    
notifications:
  - provider: Email
    to:
       - chn-student@outlook.com
    on_build_status_changed: true